### ISSUE TITLE
incorrect CFBundleVersion in v1.3.0

### ISSUE THREAD

**Issue by jormungand** [ealeksandrov/ProvisionQL#11]
Hi Evgeny,

Thanks for useful plugin!
Just installed v1.3.0 and noticed version signature mismatch in the footer: 
> ProvisionQL `v1.2.0` (Fork on GitHub)

The root cause is here:
```
....
    <key>CFBundleVersion</key>
    <string>1.2.0</string>
....
```
https://github.com/ealeksandrov/ProvisionQL/blob/1.3.0/ProvisionQL/Supporting-files/Info.plist

**Comment by ealeksandrov** [comment]
Thanks for sharing this! Will fix it in next build.
