### ISSUE TITLE
Incorrect description of expiration when less than 24h after expiration passed

### ISSUE THREAD

**Issue by kambala-decapitator** [ealeksandrov/ProvisionQL#17]
Issue title might be slightly unclear, but screenshot describes the issue: although profile has already expired, label still says "expires today".
![screen shot 2018-02-08 at 00 45 16](https://user-images.githubusercontent.com/1557784/36065437-e76d4c74-0eab-11e8-8622-8a5c9bf030d5.png)

**Comment by ealeksandrov** [comment]
Good find, thanks!

**Comment by ealeksandrov** [comment]
Good find! Fill fix soon, preparing new `ProvisionQL` release on this week.
