### ISSUE TITLE
Unable to view more than one provision profile

### ISSUE THREAD

**Issue by evgeniyd** [ealeksandrov/ProvisionQL#18]
This issue started to reproduce since latest update (s) of macOS. 

Steps to reproduce:

1. Go to `~/Library/MobileDevice/Provisioning Profiles` directory
1. Select any `.mobileprovision` or `.provisionprofile`
1. Press _Space_
1. Notice the QuickLook plugin renders the profile of your choice
1. With _Down_ or _Up_ arrow key change your selection
1. Notice the QuickLook plugin does not render the profile.

Workaround:
I was able to overcome this issue by next steps:
1. Clone the repo and setup the project to run `qlmanage` process (even though LLDB cannot attach to the process b/c of SIP, Xcode still can launch it)
1. Open _Activity Monitor_ and make sure `qlmanage` process is running
1. Do the steps 1., 2., 3., 4., from "Steps to reproduce" 
1. When you continue to do steps 5. and 6. the issue still reproduce itself
1. However, when you change the focus of the active Finder window to some other Finder window and then change it back, the next provision profile file can be previewed by the QuickLook plugin.
1. Sometimes, you need to terminate the `qlmanage` process and start over again to continue to view profiles.

Taking into account "Steps to reproduce" and "Workaround" it might be a bug in High Sierra or in the plugin itself.

OS: macOS High Sierra
Version: 10.13.3 (17D47)

**Comment by ealeksandrov** [comment]
Can you try to reinstall `ProvisionQL` and try again?
I pretty frequently browse through `Provisioning Profiles` folder and confirming now - it still works.

Also High Sierra 10.13.3 (17D47).

**Comment by evgeniyd** [comment]
I did it previously several times with no luck.
Today, I pulled latest changes from `master` and tried to install the debug build to `/Library/QuickLook/` (previously, the location was `~/Library/QuickLook/`). 

I looks better now, but I'll test it more and report here.

Thank you for quick reply.

**Comment by ealeksandrov** [comment]
Great, latest changes will be released and pushed to `homebrew cask` later this week.

**Comment by evgeniyd** [comment]
@ealeksandrov hey, I push it though some tests. It works well when the extension is placed into `/Library/QuickLook/`. I think this one can be closed.

_Off top:_ I've just realized, that I reference this amazing project in [one of my article on Medium](https://medium.com/@euginedubinin/ios-tips-maintaining-your-signing-identities-and-certificates-c04c482ca493).
