### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by orkenstein** [ealeksandrov/ProvisionQL#2]
I guess icon should look in a classic way, without "background sheet", just like Applications icons.

**Comment by ealeksandrov** [comment]
Linked question got new [answer](https://stackoverflow.com/a/36466736/840588) that works!
Will update icon generator to show plain icon image, without "background sheet".

**Comment by ealeksandrov** [comment]
This is how thumbnails look now:

![1](https://user-images.githubusercontent.com/3132438/36450548-54e4a77a-169f-11e8-82ec-767e8c60f6f9.png)

**Comment by orkenstein** [comment]
Bloody awesome!
