### ISSUE TITLE
Xcode Quick Look plugin collision

### ISSUE THREAD

**Issue by ealeksandrov** [ealeksandrov/ProvisionQL#20]
### Xcode 9.3
> Provisioning

> New Features
> Xcode provides a new quick look preview generator for provisioning profiles. The preview includes the app identifier, expiration date, certificates, device identifiers, and entitlements encoded within the profile. (37042581)

Xcode now have its own `mobileprovision` Quick Look plugin. Since it's application-provided it will override user installed plugins, including ProvisionQL.

ProvisionQL will still work for `ipa` and `xcarchive`, but if you prefer it also for `mobileprovision`, just delete Xcode's QL plugin here:
```
/Applications/Xcode.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator
```
And run
```
qlmanage -r
```

### Comparison
Xcode:
![screen shot 2018-06-15 at 11 53 51](https://user-images.githubusercontent.com/3132438/41459751-29208048-7093-11e8-8d37-84d2fd372123.png)
ProvisionQL:
![screen shot 2018-06-15 at 11 55 13](https://user-images.githubusercontent.com/3132438/41459753-29402402-7093-11e8-86fe-425f5357765f.png)

**Comment by ealeksandrov** [comment]
Additional drawback of Xcode plugin - bad appearance in dark mode (https://github.com/ealeksandrov/ProvisionQL/issues/27).
ProvisionQL since 1.6.0 have full dark mode support (https://github.com/ealeksandrov/ProvisionQL/pull/29).

**Comment by ealeksandrov** [comment]
All instances of Xcode (like multiple beta versions) can override priority for `mobileprovision` files.

Correct ProvisionQL mapping example:
```
> ~ qlmanage -m plugins | grep ProvisionQL.qlgenerator
  com.apple.xcode.archive -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.iphone.mobileprovision -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.application-and-system-extension -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.itunes.ipa -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.mobileprovision -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.provisionprofile -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
```

**Comment by danpashin** [comment]
Xcode 16 has moved it's generator to `${XCODE_PATH}/Contents/PlugIns/ProvisoningProfileQuicklookExtension.appex`. Related to #55
