### ISSUE TITLE
iPad App Icon not show

### ISSUE THREAD

**Issue by ipad4** [ealeksandrov/ProvisionQL#22]
iPad App Icon not show

**Comment by ealeksandrov** [comment]
Can you send example `ipa` to my email and describe expected results?

**Comment by ealeksandrov** [comment]
Thanks, received and confirmed. Will debug once I have free time, sorry for possible delay.

**Comment by ealeksandrov** [comment]
@ipad4 [version 1.5.0](https://github.com/ealeksandrov/ProvisionQL/releases/tag/1.5.0) with fix for iPad-only apps released.
