### ISSUE TITLE
Cannot see provisioning info for .ipa with SDK 12.0

### ISSUE THREAD

**Issue by NonnEmilia** [ealeksandrov/ProvisionQL#24]
Starting from SDK: iphoneos12.0 quick look doesn't show any info about provisioning for `.ipa` files.

SDK 12.0:
![immagine](https://user-images.githubusercontent.com/2818194/45869811-afa81e80-bd89-11e8-87f3-9d096cd6d009.png)

SDK 10.3 (but it works also with 11.2):
![immagine](https://user-images.githubusercontent.com/2818194/45869773-93a47d00-bd89-11e8-988b-6c59c446a890.png)

**Comment by ealeksandrov** [comment]
Thanks for report, will check!

**Comment by NonnEmilia** [comment]
Ok: I found the issue.
I was using "Automatically manage signing & Provisioning Profile" and XCode didn't create one...
I manually assigned the provisioning profile and now it correctly displays the info.

Thank you for your fast reply and sorry for the useless issue...
You can close it.
