### ISSUE TITLE
Add warning about Xcode plugin to Homebrew install flow

### ISSUE THREAD

**Issue by abotkin-cpi** [ealeksandrov/ProvisionQL#27]
Using macOS 10.14 (18A389) with dark mode with the latest version of ProvisionQL (1.5.0), the preview displayed is hard to read due to the main text being shifted to a very light grey that blends in with the blur of the Quick Look window.  This only occurs when in dark mode & colors are a readable black when in light mode.

![provisionqldarkmode](https://user-images.githubusercontent.com/25309848/50859736-004b8380-1349-11e9-9ac2-4ed7b619a096.png)

**Comment by ealeksandrov** [comment]
Thanks for report.
But - you're looking not at ProvisionQL, it's bundled Xcode plugin. Please check https://github.com/ealeksandrov/ProvisionQL/issues/20

In my test ProvisionQL works fine in dark mode:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/3132438/50960132-b0e68e00-14d5-11e9-91eb-ae69ce73ee4b.png">

**Comment by abotkin-cpi** [comment]
Any chance the instructions/warning in #20 could be incorporated into the install script via Homebrew similar to how other tools in Homebrew give warnings about path additions needed for best functionality?  When installing via Homebrew today, there is no information provided to the user that addition setup requirements may be necessary if they want it to work for provisioning profiles.

```
allegseu:ios abotkin$ brew cask install provisionql
==> Satisfying dependencies
==> Downloading https://github.com/ealeksandrov/ProvisionQL/releases/download/1.5.0/ProvisionQL.zip
Already downloaded: /Users/abotkin/Library/Caches/Homebrew/downloads/a06bb9a4cde5f73090266d943db25b07053a8a2f3a17d75e746574be905624fe--ProvisionQL.zip
==> Verifying SHA-256 checksum for Cask 'provisionql'.
==> Installing Cask provisionql
==> Moving QuickLook Plugin 'ProvisionQL.qlgenerator' to '/Users/abotkin/Library/QuickLook/ProvisionQL.qlgenerator'.
🍺  provisionql was successfully installed!
```

**Comment by ealeksandrov** [comment]
Added `caveat` in [1.6.0](https://github.com/ealeksandrov/ProvisionQL/releases/tag/1.6.0) on Homebrew Cask:

```
> ~/Documents/dev/ProvisionQL brew cask install provisionql
==> Caveats
To prevent mobileprovision QuickLook override by Xcode: https://github.com/ealeksandrov/ProvisionQL/issues/20

==> Satisfying dependencies
==> Downloading https://github.com/ealeksandrov/ProvisionQL/releases/download/1.6.0/ProvisionQL.zip
Already downloaded: /Users/ealeksandrov/Library/Caches/Homebrew/downloads/b33882767370c967ffc70a8d9435fad930ca4db3d3f3775f9f31cc2512715051--ProvisionQL.zip
==> Verifying SHA-256 checksum for Cask 'provisionql'.
==> Installing Cask provisionql
==> Moving QuickLook Plugin 'ProvisionQL.qlgenerator' to '/Users/ealeksandrov/Library/QuickLook/ProvisionQL.qlgenerator'.
🍺  provisionql was successfully installed!
```
