### ISSUE TITLE
[Bug/Feature Request] Dark mode support

### ISSUE THREAD

**Issue by 916253** [ealeksandrov/ProvisionQL#28]
Dark mode on macOS Mojave causes the text to change colors, but the background color remains the same, resulting in clashing colors which causes the text to become unreadable: 
![image](https://user-images.githubusercontent.com/3783580/53868064-61db4780-3fb2-11e9-91c1-bffce43ec78d.png)

**Comment by ealeksandrov** [comment]
Strange, dark mode looks fine for me:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/3132438/53868653-90cfd880-4007-11e9-9ca2-46a335b464ff.png">

(+ https://github.com/ealeksandrov/ProvisionQL/issues/27#issuecomment-453034801)

macOS 10.14.3

**Comment by 916253** [comment]
Interesting-- I tried this on multiple machines, one on 10.14.3, and another on 10.14.4 Beta (18E194d)
both exhibited the same results. 
Would it be possible for you to force the plugin to always use light mode (via bool `NSRequiresAquaSystemAppearance` or similar)?

**Comment by ealeksandrov** [comment]
I don't remember doing any special settings, but I'll check on other macs anyway.

Thanks for sharing your solution :)

**Comment by ealeksandrov** [comment]
Full dark mode support added in [#29](https://github.com/ealeksandrov/ProvisionQL/pull/29) and released in [1.6.0](https://github.com/ealeksandrov/ProvisionQL/releases/tag/1.6.0) on Homebrew Cask.

Let's see if it fixes all your cases :)

**Comment by 916253** [comment]
Yeah, that seems to have fixed everything, awesome! 
![image](https://user-images.githubusercontent.com/3783580/57012928-04d0cc00-6bc6-11e9-82d3-bd0a619d163c.png)
