### ISSUE TITLE
Failed on macOS Catalina beta1

### ISSUE THREAD

**Issue by paopaosa** [ealeksandrov/ProvisionQL#30]
I tried reload the plugin. But it is failed load and it shows below warnings.

-------------------------------------------------------------------------
qlmanage -r
dyld: warning, LC_RPATH @executable_path/../Frameworks in /usr/bin/qlmanage being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /usr/bin/qlmanage being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
dyld: warning, LC_RPATH @executable_path/../Frameworks in /usr/bin/qlmanage being ignored in restricted program because of @executable_path (Codesign main executable with Library Validation to allow @ paths)
qlmanage: resetting quicklookd

**Comment by ygit** [comment]
I'm facing the same issue on macOS Catalina beta1. Any fixes planned to release @ealeksandrov ?

**Comment by ealeksandrov** [comment]
Thanks for report. Looks like a codesign/notarize issue.
Will look into this on next week.

**Comment by ealeksandrov** [comment]
It's turned out to be really complex issue related to macOS security updates.

I see that MacOS Catalina adds Thumbnail Extensions - https://developer.apple.com/documentation/quicklookthumbnailing. Maybe its goal is to replace old QuickLook generators?

Still looking into it.

**Comment by TinyQ** [comment]
![image](https://user-images.githubusercontent.com/3217732/68030060-98a95f00-fcf3-11e9-8987-1babe57a109f.png)

Show this warning when use it.

**Comment by ealeksandrov** [comment]
Please try this build and let me know:

[ProvisionQL.qlgenerator.zip](https://github.com/ealeksandrov/ProvisionQL/files/3798843/ProvisionQL.qlgenerator.zip)

**Comment by TinyQ** [comment]
> Please try this build and let me know:
> 
> [ProvisionQL.qlgenerator.zip](https://github.com/ealeksandrov/ProvisionQL/files/3798843/ProvisionQL.qlgenerator.zip)

This package is work 👏, and my system is macOS Catalina 10.15. 🎉🎉🎉

**Comment by ealeksandrov** [comment]
I don't know what is the difference, but I just added code signing (#32) and repeated notarization that never worked before (on Catalina beta). Maybe final Catalina release have some additional QL updates. Or notarization system was updated. Or I made a mistake on previous try :)

Anyway, ProvisionQL 1.6.1 update is now available on homebrew cask.
