### ISSUE TITLE
MacOS Catalina 10.15 Issues

### ISSUE THREAD

**Issue by smolster** [ealeksandrov/ProvisionQL#33]
I'm having trouble getting the plugin to work at all (for any of the supported filetypes) on my machine running macOS 10.15 Catalina. Install process goes fine, but whenever I quick look an IPA or an xcarchive, I just see the default quick look view.

Tried re-installing, but that didn't help. I'm not sure how to troubleshoot further. Is there a place I can look to see Quick Look errors?

Thanks for any help!

**Comment by ealeksandrov** [comment]
Hi!
That's strange, can you confirm that you're using latest version?

You can try something like this (https://aleksandrov.ws/2014/02/25/osx-quick-look-plugin-development/):
```sh
# generate preview
qlmanage -p 1234.mobileprovision
# generate thumbnail
qlmanage -t 1234.mobileprovision
```

And to check file types and plugins associations:
```sh
qlmanage -m plugins | grep ProvisionQL.qlgenerator
```

**Comment by Kiran-B** [comment]
@smolster Do you have Xcode installed? Perhaps you may want to look into this: [Xcode Quick Look plugin collision](https://github.com/ealeksandrov/ProvisionQL/issues/20)

**Comment by jaybowong** [comment]
@ealeksandrov 
I'm using Catalina 10.15.3.
After running `qlmanage -p y.mobileprovision`, I got this.
```
Testing Quick Look preview with files:
	/Users/x/y.mobileprovision
2020-03-16 18:33:34.564 qlmanage[64807:498126] Failed to read provisioning profile "/Users/x/y.mobileprovision"
2020-03-16 18:33:34.637 qlmanage[64807:498126] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7303, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2020-03-16 18:33:34.837 qlmanage[64807:498126] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x14f1f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

**Comment by ealeksandrov** [comment]
@jaybowong 
I use same macOS 10.15.3 with no QL issues.

From error log looks like plugin is currently installed but `qlmanage` somehow can't read input test file. Never seen this kind of error before.
I'll search more but can't suggest anything now. Let us know if you find the solution.

**Comment by ealeksandrov** [comment]
@jaybowong 
Can you also try `qlmanage -m plugins | grep provision`? And maybe test ipa/archive?

I just noticed that you have `com.apple.iphone.mobileprovision` listed but missing `com.apple.mobileprovision`.

Maybe Xcode is [overriding](#20) `.mobileprovision` QL as @Kiran-B suggested above.

My output is:
```
> ~ qlmanage -m plugins | grep ProvisionQL.qlgenerator
  com.apple.iphone.mobileprovision -> /Users/x/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.application-and-system-extension -> /Users/x/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.itunes.ipa -> /Users/x/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.provisionprofile -> /Users/x/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.xcode.archive -> /Users/x/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.mobileprovision -> /Users/x/Library/QuickLook/ProvisionQL.qlgenerator (59)
```

BTW, I have same 2 errors for `bootstrap_register` in log, but preview works fine, so they are unrelated.

**Comment by jaybowong** [comment]
After running `qlmanage -m plugins | grep provision`:

```
  com.apple.iphone.mobileprovision -> /Users/x/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.provisionprofile -> /Applications/Xcode-11.3.1.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator (15705 - loaded)
  com.apple.mobileprovision -> /Applications/Xcode-11.3.1.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator (15705 - loaded)
```

In `/Applications` I got `Xcode-10.2.1.app`, `Xcode-11.2.1.app` and `Xcode-11.3.1.app` because my work needs them. 
I tried to rename `Xcode-11.3.1.app` to `Xcode.app` and reinstall ProvisionQL, the problem still exists.

**Comment by ealeksandrov** [comment]
You can re/move only `DVTProvisioningProfileQuicklookGenerator.qlgenerator` inside those Xcodes. And run `qlmanage -r` after that.

**Comment by wonderffee** [comment]
Similar problem with ipa file. Maybe because I installed Xcode11.5 on my Mac recently.
Finally solve it with follow command
➜  QuickLook xcode-select --print-path
/Applications/Xcode11.2.1.app/Contents/Developer
➜  QuickLook sudo xcode-select --switch /Applications/Xcode11.5.app/Contents/Developer

**Comment by ealeksandrov** [comment]
Closing this as I don't see any new bug reports and issue looks resolved.
Some additional info can be found in https://github.com/ealeksandrov/ProvisionQL/issues/37

Let's see what macOS 11 brings to us 🙂
