### ISSUE TITLE
Unrecognized selector and Permission denied errors

### ISSUE THREAD

**Issue by fingersakimbo** [ealeksandrov/ProvisionQL#37]
I just installed, and it's not working for me.  I looked at some of your other issues to try to find troubleshooting information. When I try
```
qlmanage -p foo.mobileprovision
```

I get:
```
Testing Quick Look preview with files:
	foo.mobileprovision
2020-07-27 13:22:25.793 qlmanage[86947:11580548] -[NSCompositeAppearance dvt_hasDarkAppearance]: unrecognized selector sent to instance 0x7fcd4b70b070
2020-07-27 13:22:25.939 qlmanage[86947:11580548] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6d03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2020-07-27 13:22:26.001 qlmanage[86947:11580548] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x1411f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

I'm on Catalina 10.15.6, and Xcode 11.6

**Comment by herman602** [comment]
I encounter the same issue and the same error message. However, I can preview the IPA file but cannot preview mobileprovision file.

**Comment by ealeksandrov** [comment]
I remember `bootstrap_register` errors for a long time now. They don't impact anything.
In my test on 10.15.6 it worked fine just now:
```
> ~ qlmanage -p Desktop/test.mobileprovision
Testing Quick Look preview with files:
	Desktop/test.mobileprovision
2020-07-28 10:05:49.429 qlmanage[1703:24467] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x14b03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2020-07-28 10:05:49.527 qlmanage[1703:24467] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xcf1f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

So your issue is just this line:
```
-[NSCompositeAppearance dvt_hasDarkAppearance]: unrecognized selector sent to instance 0x7fcd4b70b070
```
In case it may be related I've tried light/dark/auto system appearances and all work fine for me.

@fingersakimbo can you also try `ipa` (or `xcarchive`) preview? And check your `qlmanage -m plugins | grep ProvisionQL.qlgenerator` output?
@herman602 you removed Xcode's generator, right? Can you also recheck your plugins mapping?

**Comment by ealeksandrov** [comment]
Correct plugins mapping example:
```
> ~ qlmanage -m plugins | grep ProvisionQL.qlgenerator
  com.apple.xcode.archive -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.iphone.mobileprovision -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.application-and-system-extension -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.itunes.ipa -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.mobileprovision -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.provisionprofile -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (59)
```

**Comment by herman602** [comment]
@ealeksandrov Thank you for your response. I have removed the Xcode's generator by this command 

> sudo rm -rf /Applications/Xcode.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator

And here is the plugins mapping (_qlmanage -m plugins | grep ProvisionQL.qlgenerator_)
 > 
  > com.apple.iphone.mobileprovision -> /Users/andy/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.application-and-system-extension -> /Users/andy/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.itunes.ipa -> /Users/andy/Library/QuickLook/ProvisionQL.qlgenerator (59)
  com.apple.xcode.archive -> /Users/andy/Library/QuickLook/ProvisionQL.qlgenerator (59)

**Comment by ealeksandrov** [comment]
But where is `com.apple.mobileprovision`? Run `qlmanage -m plugins | grep provision`
Maybe you have additional Xcode instances, recent betas?

**Comment by herman602** [comment]
@ealeksandrov Yes. You are right. I just removed the `DVTProvisioningProfileQuicklookGenerator.qlgenerator` of Xcode Beta and run `qlmanage -r` again. Everything works well.

**Comment by ealeksandrov** [comment]
@fingersakimbo I suspect you have same issue - https://github.com/ealeksandrov/ProvisionQL/issues/20

**Comment by fingersakimbo** [comment]
It doesn't seem that I'm able to get rid of the Apple providers.
```
>>> qlmanage -m plugins | grep provision
  com.apple.iphone.mobileprovision -> /Users/kyle/Library/Quicklook/Provisioning.qlgenerator (1.0.4)
  com.apple.provisionprofile -> /Applications/Xcode.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator (16131.1)
  com.apple.mobileprovision -> /Applications/Xcode.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator (16131.1)
>>> sudo rm -rf /Applications/Xcode.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator
>>> qlmanage -r
qlmanage: resetting quicklookd
>>> qlmanage -m plugins | grep provision
  com.apple.iphone.mobileprovision -> /Users/kyle/Library/Quicklook/Provisioning.qlgenerator (1.0.4)
  com.apple.provisionprofile -> /Applications/Xcode.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator (16131.1)
  com.apple.mobileprovision -> /Applications/Xcode.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator (16131.1)
>>>
```

BUT ... the comment above made me try an IPA.  When I did, I got a prompt asking if I wanted to trust Provisioning.qlgenerator, and gave me the option to open it anyway. I didn't get that when I tried a provisioning profile.  When I told it I would allow it, viewing the IPA worked, and returning to a .mobileprovision file worked as well.

So, I'm good. It just took the additional step of trying a new file type to ask for permission.

thanks!

**Comment by ealeksandrov** [comment]
Interesting, that's unknown step for me 🤔
Thanks for sharing!
