### ISSUE TITLE
Retina icon

### ISSUE THREAD

**Issue by sindresorhus** [ealeksandrov/ProvisionQL#4]
The icon in the preview is not shown in retina:

![provisionql](https://cloud.githubusercontent.com/assets/170270/2901291/0cb3eabc-d5d3-11e3-86d4-91ea6f4ee8dc.png)

**Comment by ealeksandrov** [comment]
[Version 1.5.0](https://github.com/ealeksandrov/ProvisionQL/releases/tag/1.5.0) with updates for icons extraction released.
Now it will prefer 60x60@2x for iPhone and max size for iPad.
