### ISSUE TITLE
QuickLook does not work on macOS BigSur

### ISSUE THREAD

**Issue by JanC** [ealeksandrov/ProvisionQL#40]
hey,
I can't make the `ProvisionQL` to work on macOS BigSur. I installed it via Homebrew

```
brew install provisionql
```

My Xcode is here
```
xcode-select -p
/Applications/Xcode-12.1.app/Contents/Developer
```

I did remove the default QL for:

```
rm /Applications/Xcode-12.1.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator
```

```
qlmanage -r

qlmanage -m plugins | grep ProvisionQL.qlgenerator
  com.apple.iphone.mobileprovision -> /Users/jan/Library/QuickLook/ProvisionQL.qlgenerator (64)
  com.apple.application-and-system-extension -> /Users/jan/Library/QuickLook/ProvisionQL.qlgenerator (64)
  com.apple.xcode.archive -> /Users/jan/Library/QuickLook/ProvisionQL.qlgenerator (64)
```

But when I quick look an `.ipa` or a `.mobileprovision`, I don't get any preview

<img width="821" alt="Screenshot 2020-11-15 at 20 42 12" src="https://user-images.githubusercontent.com/707703/99194980-38148500-2783-11eb-9030-7ff000195f03.png">

<img width="942" alt="Screenshot 2020-11-15 at 20 42 27" src="https://user-images.githubusercontent.com/707703/99194984-3fd42980-2783-11eb-9ce7-a3cef0c7e773.png">

any tips?

**Comment by carlosefonseca** [comment]
I was having the same issue. After deleting the Xcode generator, the mobileprovision still didn't appear. Then it hit me that I was trying to view a profile encrypted with `fastlane match`… after decrypting it, it worked 🙂

**Comment by JanC** [comment]
In my case I use normal profiles without match. The Xcode QL plugin works on them

**Comment by JeansHuang** [comment]
It works on Monterey.

**Comment by ealeksandrov** [comment]
@JanC sorry for late answer! Probably your UTI/plugins list is missing 3 lines, most likely you had different version of Xcode installed in the system (or even lying in the trash).

You can check for Xcode generators with:
```
> qlmanage -m plugins | grep Xcode
  com.apple.mobileprovision -> /Users/ealeks/.Trash/Xcode-13.1.0.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator (19457)
  com.apple.provisionprofile -> /Users/ealeks/.Trash/Xcode-13.1.0.app/Contents/Library/QuickLook/DVTProvisioningProfileQuicklookGenerator.qlgenerator (19457)
```

And correct setup for ProvisionQL should look like this:
```
> qlmanage -m plugins | grep ProvisionQL.qlgenerator
  com.apple.xcode.archive -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (64)
  com.apple.iphone.mobileprovision -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (64)
  com.apple.application-and-system-extension -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (64)
  com.apple.itunes.ipa -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (64)
  com.apple.mobileprovision -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (64)
  com.apple.provisionprofile -> /Users/ealeks/Library/QuickLook/ProvisionQL.qlgenerator (64)
```

**Comment by ealeksandrov** [comment]
Closing as plugin compatibility confirmed on macOS Big Sur and Monterey.

**Comment by JanC** [comment]
@ealeksandrov thanks for your answer, I'll give it a try later

cheers
