### ISSUE TITLE
Not working on macOS Ventura

### ISSUE THREAD

**Issue by Am1nCmd** [ealeksandrov/ProvisionQL#44]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/15339573/177505976-749453b7-7749-40db-813b-de537124ffcc.png">

**Comment by lg8294** [comment]
me too

**Comment by ealeksandrov** [comment]
Works for me on latest macOS Ventura:

<img width="755" src="https://user-images.githubusercontent.com/3132438/223956596-f315d2db-54ed-43b9-9595-5cf4a2d8192f.png">

Please take a look at debugging steps in #33, #37, #40.
I'm closing the issue for now, but feel free to comment with more input.
