### ISSUE TITLE
Improve mobileprovision preview visiblity in dark mode

### ISSUE THREAD

**Issue by myonlylonely** [ealeksandrov/ProvisionQL#48]
The visibility of the mobileprovision file preview in dark mode is quite poor. Please consider changing the text to a different color.

<img width="604" alt="image" src="https://github.com/ealeksandrov/ProvisionQL/assets/8188177/bb78a28e-6372-469b-9b1e-861a39ba2cf3">

**Comment by ealeksandrov** [comment]
Hey!
ProvisionQL has Dark Mode support since 1.6.0 (https://github.com/ealeksandrov/ProvisionQL/pull/29).
That's Xcode's own plugin on your screenshot. It overrides ProvisionQL, look here for a fix:
- https://github.com/ealeksandrov/ProvisionQL/issues/20.

**Comment by myonlylonely** [comment]
Nice!
