### ISSUE TITLE
Unable to inspect ipa and apps anymore

### ISSUE THREAD

**Issue by tonyxiao** [ealeksandrov/ProvisionQL#5]
With the latest version of ProvisionQL I'm not able to inspect IPA and .app 's anymore. It used to work before so I'm rather confused. Inspecting provisioning profile files directly still works. ProvisionQL hasn't updated in a while, i'm suspecting change is coming from OS X's side?

**Comment by ealeksandrov** [comment]
Please verify that current update is working for you.

**Comment by tonyxiao** [comment]
Yep, totally awesome, works again!
