### ISSUE TITLE
Low contrast in dark mode

### ISSUE THREAD

**Issue by kzietek** [ealeksandrov/ProvisionQL#53]
In dark mode, values are displayed as white text on bright gray background which makes them unreadable. Font color for values and headers needs to be adjusted.

Edit: I pixelized some sensitive values on the image.

![Pobrane_rzeczy](https://github.com/ealeksandrov/ProvisionQL/assets/11509284/16c4c2ae-a6d0-401a-84c0-b042449f6bce)

**Comment by ealeksandrov** [comment]
Hey!
ProvisionQL has Dark Mode support since 1.6.0 (https://github.com/ealeksandrov/ProvisionQL/pull/29).
That's Xcode's own plugin on your screenshot. It overrides ProvisionQL, look here for a fix:
- https://github.com/ealeksandrov/ProvisionQL/issues/20.
