### ISSUE TITLE
IPA Quicklook doesn't works on macOS Sequoia

### ISSUE THREAD

**Issue by cristopherturazza** [ealeksandrov/ProvisionQL#56]
After Sequoia upgrade, ipad quicklook doesn't works (it opens the standard quicklook window).
.mobileprovision still works.

**Comment by cristopherturazza** [comment]
> After Sequoia upgrade, ipad quicklook doesn't works (it opens the standard quicklook window). .mobileprovision still works.

Probably referred to 55 issue, if confirmed i close the issue.

**Comment by ealeksandrov** [comment]
Thanks for report, let's keep it in #55.
