### ISSUE TITLE
Unable to view .ipa generated for Ad Hoc distribution

### ISSUE THREAD

**Issue by rcritz** [ealeksandrov/ProvisionQL#8]
I have a client for whom I deliver an app exported for Ad-Hoc distribution. It's key that I be able to see the device IDs that are provisioned in the app. `ProvisionQL` just shows a spinner for 15-20 seconds and then shows me nothing. `ipaql` works but I'd rather be able to switch to `ProvisionQL` because it does more. Any ideas?

I can arrange to provide you with a copy of the relevant .ipa directly if you want it.

**Comment by ealeksandrov** [comment]
Sounds interesting but I'm pretty busy currently. I'll re-check ad-hoc inspecting locally and ping you in couple of weeks.
Thanks for reporting!

P.S. If you have free time and interested in debugging - check instruction here: https://aleksandrov.ws/2014/02/25/osx-quick-look-plugin-development/

**Comment by ealeksandrov** [comment]
Received ipa to reproduce issue, confirmed. Will give update later after debugging.

**Comment by ealeksandrov** [comment]
https://stackoverflow.com/questions/33423993/hanging-nstask-using-waituntilexit.
Fixed in 2bbe66b068c81721d6102211f92fc6ce5388a280.
Released as [1.4.1](https://github.com/ealeksandrov/ProvisionQL/releases/tag/1.4.1).
