### ISSUE TITLE
Device description

### ISSUE THREAD

**Issue by andredsp** [ealeksandrov/ProvisionQL#9]
Very nice quick look plugin!

I just have one question. I'm previewing an adhoc .mobileprovision file and the devices are shown as "unknown". What should I do to add description to the devices?

Thank you.

**Comment by ealeksandrov** [comment]
They were stored in Xcode user defaults: `com.apple.dt.XCode -> DVTSavediPhoneDevices` and they are not there now :(

In Xcode 8 this info moved to [DVTDeviceTokens](https://stackoverflow.com/questions/46808734/xcode-device-data-like-dvtdevicetokens-for-appletv-and-applewatch), but now in Xcode 9 I can't find it at all - (`defaults read com.apple.dt.Xcode`). With no obvious solution it's better to just remove useless columns.

Thangs for bringing attention and sorry for late reply.
